[
{
	"idQuimico":2,
	"nombreQuimico":"Manuel",
	"apellidoPaternoQuimico":"Jimenez",
	"apellidoMaternoQuimico":"Gordillo",
	"loginQuimico":"admin@nuba.com",
	"contraseñaQuimico":"123456",
	"api_key":"cbf09d9e68ac7984e1821ff3b1d253b2",
	"emailQuimico":"hflores@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Hospital Upaep",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"JESUS EDUARDO", 
	"apellidoPaternoQuimico":"Coxca",
	"apellidoMaternoQuimico":"Flores",
	"loginQuimico":"jecoxca@nubaclinica.com", 
	"contraseñaQuimico":"jeco123456",
	"api_key":"bdd59fad7177e604da7e4d024b98ed17",
	"emailQuimico":"jecoxca@nubaclinica.com", 
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Clínica Xicotepec",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":26,
	"nombreQuimico":"REYNA ITZEL ", 
	"apellidoPaternoQuimico":"MELO",
	"apellidoMaternoQuimico":"GONZALES",
	"loginQuimico":"itzelmg@nubaclinica.com", 
	"contraseñaQuimico":"delG6",
	"api_key":"87a8915db42c26f762ce6cc433fd56ec",
	"emailQuimico":"jecoxca@nubaclinica.com", 
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Hospital Angeles México",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Test User",
	"apellidoPaternoQuimico":"Jimenez",
	"apellidoMaternoQuimico":"Gordillo",
	"loginQuimico":"test@nuba.com",
	"contraseñaQuimico":"123456",
	"api_key":"cbf09d9e68ac7984e1821ff3b1d253b2",
	"emailQuimico":"hflores@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Hospital Upaep",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Q.F.B. Mariana Elizabeth",
	"apellidoPaternoQuimico":"Muciño",
	"apellidoMaternoQuimico":"Bolaños",
	"loginQuimico":"marem@nuba.com",
	"contraseñaQuimico":"meri4",
	"api_key":"2abf48774f346d08b48bd9f3de38beef",
	"emailQuimico":"marem@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Hospital Toluca",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Usuario",
	"apellidoPaternoQuimico":"",
	"apellidoMaternoQuimico":"",
	"loginQuimico":"gdc@nuba.com",
	"contraseñaQuimico":"difusion",
	"api_key":"e70beaed4ba35be4a8a91cd75dea8a17",
	"emailQuimico":"gdc@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"GDC",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Irving",
	"apellidoPaternoQuimico":"Sanchez",
	"apellidoMaternoQuimico":"",
	"loginQuimico":"irsa@nuba.com",
	"contraseñaQuimico":"vidaN",
	"api_key":"865166de87fc2573e413916451e0b758",
	"emailQuimico":"irsa@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Centro Oncologico ISSEMYM de Toluca",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Grace",
	"apellidoPaternoQuimico":"Villalobos",
	"apellidoMaternoQuimico":"",
	"loginQuimico":"gravi@nuba.com",
	"contraseñaQuimico":"zuelW",
	"api_key":"e5a9bf127f63b63b77c0ef1e77518139",
	"emailQuimico":"irsa@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Hospital de Niño y Adolescente Morelense",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Sergio",
	"apellidoPaternoQuimico":"Jimenez",
	"apellidoMaternoQuimico":"",
	"loginQuimico":"serji@nuba.com",
	"contraseñaQuimico":"musiR",
	"api_key":"c4f6375a56de03eb3dbae83dc52b566e",
	"emailQuimico":"serji@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Centro Medico Puerta de Hierro",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":2,
	"nombreQuimico":"Jose Luis", 
    "apellidoPaternoQuimico":" Aguilar", 
    "apellidoMaternoQuimico":"Vazquez", 
    "loginQuimico":"joslvr@nuba.com",
	"contraseñaQuimico":"list1",
	"api_key":"c4f6375a56de03eb3dbae83dc52b566e",
	"emailQuimico":"joslvr@nuba.com",
	"telefonoQuimico":2323232323,
	"extencionQuimico":2333,
	"nombreHospital":"Star Médica Lomas Verdes",
	"idTurno":1,
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico":33,
	"nombreQuimico": "Usuario dos",
    "apellidoPaternoQuimico": "semar",
    "apellidoMaternoQuimico": "",
    "loginQuimico": "semar2@nuba.com",
    "contraseñaQuimico": "adesQ",
    "emailQuimico": "semar@nuba.com",
    "telefonoQuimico": "5526251700",
    "extensionQuimico": "0000002222",
    "idHospital": 16,
    "idTurno": 1,
    "api_key": "8594c98fa94dd9d7b28dd6d3ddff2b13",
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico": 32,
    "nombreQuimico": "Usuario uno",
    "apellidoPaternoQuimico": "semar",
    "apellidoMaternoQuimico": "",
    "loginQuimico": "semar1@nuba.com",
    "contraseñaQuimico": "lizal",
    "emailQuimico": "semar1@nuba.com",
    "telefonoQuimico": "5526251700",
    "extensionQuimico": "0000002222",
    "idHospital": 16,
    "idTurno": 1,
    "api_key": "f830d34ba2bdd699c6182378378530c2",
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico": 34,
    "nombreQuimico": "Julio",
    "apellidoPaternoQuimico": "Cesar",
    "apellidoMaternoQuimico": "Perez",
    "loginQuimico": "jucep@nuba.com",
    "contraseñaQuimico": "lanzR",
    "idHospital": 17,
    "idTurno": 1,
    "api_key": "b21c60f6f29a2e93de8452417204307e",
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico": 35,
    "nombreQuimico": "Eva",
    "apellidoPaternoQuimico": "Lopez",
    "apellidoMaternoQuimico": "",
    "loginQuimico": "evalo@nuba.com",
    "contraseñaQuimico": "camunu",
    "emailQuimico": "evalo@nuba.com",
    "telefonoQuimico": "5526251700",
    "extensionQuimico": "0000002222",
    "idHospital": 18,
    "idTurno": 1,
    "api_key": "102de0b1fd30a63119a08c7b7db55c05",
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
},
{
	"idQuimico": 36,
    "nombreQuimico": "Lizeth",
    "apellidoPaternoQuimico": "Contreras",
    "apellidoMaternoQuimico": "",
    "loginQuimico": "lizco@nuba.com",
    "contraseñaQuimico": "imea5",
    "emailQuimico": "evalo@nuba.com",
    "telefonoQuimico": "5526251700",
    "extensionQuimico": "0000002222",
    "idHospital": 19,
    "idTurno": 1,
    "api_key": "fcf1a14e373fddd4e5a4f01f763918a2",
	"permisos":{
		"login":true,
		"administrador":false,
		"conciliacion":true,
		"altas_h":true,
		"salidas_h":true,
		"idoneidad":true,
		"interaccion":true,
		"config":true
	}
}

]