<?php
/**
 * Database configuration
 */
if(!defined('DB_USERNAME'))define('DB_USERNAME', 'root');
if(!defined('DB_PASSWORD'))define('DB_PASSWORD', '');
if(!defined('DB_HOST'))define('DB_HOST', 'localhost');
if(!defined('DB_NAME'))define('DB_NAME', 'nuba');
//API 
if(!defined('MAX_ITERATIONS'))define('MAX_ITERATIONS', 50);
//DB Constants
if(!defined('PATIENT_INTERN'))define('PATIENT_INTERN', 1);
if(!defined('PATIENT_SIGNED_OUT'))define('PATIENT_SIGNED_OUT', 2);
if(!defined('ALERT_TYPE_CD_INCOMPLETE'))define('ALERT_TYPE_CD_INCOMPLETE', 1);
if(!defined('ALERT_TYPE_DF_INCOMPLETE'))define('ALERT_TYPE_DF_INCOMPLETE', 2);
if(!defined('ALERT_TYPE_SUITABILITY_INCOMPLETE'))define('ALERT_TYPE_SUITABILITY_INCOMPLETE', 3);
if(!defined('ALERT_ALLOW'))define('ALERT_ALLOW', 1);
if(!defined('ALERT_ID_CD_INCOMPLETE'))define('ALERT_ID_CD_INCOMPLETE', 3);
if(!defined('ALERT_STATUS_DF_SUITABILITY'))define('ALERT_STATUS_DF_SUITABILITY', 2);
if(!defined('ALERT_ID_DF_INCOMPLETE_AND_CONCILIATION'))define('ALERT_ID_DF_INCOMPLETE_AND_CONCILIATION', 1);
// 100  USER VALUES
if(!defined('USER_CREATED_SUCCESSFULLY'))	define('USER_CREATED_SUCCESSFULLY', 100);
if(!defined('USER_CREATE_FAILED'))	define('USER_CREATE_FAILED', 101);
if(!defined('USER_ALREADY_EXISTED'))	define('USER_ALREADY_EXISTED', 102);
if(!defined('ITEM_ALREADY_EXISTED'))	define('ITEM_ALREADY_EXISTED', 302);
if(!defined('USER_TELEPHONE_WRONG'))	define('USER_TELEPHONE_WRONG', 103 );
if(!defined('USER_EXTENSION_WRONG'))	define('USER_EXTENSION_WRONG', 104);
if(!defined('HOSPITAL_ID_DOES_NOT_EXIST'))	define('HOSPITAL_ID_DOES_NOT_EXIST', 105);
if(!defined('SHIFT_ID_DOES_NOT_EXIST'))	define('SHIFT_ID_DOES_NOT_EXIST', 106);
//Group Constants
if(!defined('GROUP_CREATED_SUCCESSFULLY'))	define('GROUP_CREATED_SUCCESSFULLY', 200);
if(!defined('GROUP_CREATE_FAILED'))	define('GROUP_CREATE_FAILED', 201);
if(!defined('GROUP_ALREADY_EXISTED'))	define('GROUP_ALREADY_EXISTED', 202);
//Hospital Constants
if(!defined('HOSPITAL_CREATED_SUCCESSFULLY'))	define('HOSPITAL_CREATED_SUCCESSFULLY', 300);
if(!defined('HOSPITAL_ALREADY_EXISTED'))	define('HOSPITAL_ALREADY_EXISTED', 301);
if(!defined('HOSPITAL_CREATE_FAILED'))	define('HOSPITAL_CREATE_FAILED', 302);
if(!defined('PHONE_INVALID_FORMAT'))	define('PHONE_INVALID_FORMAT', 303);
if(!defined('URL_INVALID_FORMAT'))	define('URL_INVALID_FORMAT', 304);
// Clinical data Consants
if(!defined('CD_CREATED_SUCCESSFULLY'))	define('CD_CREATED_SUCCESSFULLY', 100);
if(!defined('CD_PATIENT_NOT_EXISTS'))	define('CD_PATIENT_NOT_EXISTS', 101);
if(!defined('CD_INVALID_FIELDS'))	define('CD_INVALID_FIELDS', 102);	
if(!defined('CD_CREATE_OK_W_ALERTS'))	define('CD_CREATE_OK_W_ALERTS', 103);
if(!defined('CD_UPDATE_OK_W_ALERTS'))	define('CD_UPDATE_OK_W_ALERTS', 103);
if(!defined('CD_UPDATE_OK'))	define('CD_UPDATE_OK', 100);
if(!defined('CD_DELETE_OK'))	define('CD_DELETE_OK', 100);
if(!defined('CD_UPDATE_FAILED'))	define('CD_UPDATE_FAILED', 111);
if(!defined('CD_UPDATE_ID_NOT_FOUND'))	define('CD_UPDATE_ID_NOT_FOUND', 104);
if(!defined('CD_NOT_FOUND'))	define('CD_NOT_FOUND', 104);
if(!defined('CD_PETITION_RECEIVED'))	define('CD_PETITION_RECEIVED', 100);
if(!defined('CD_NOT_EXISTS'))    define('CD_NOT_EXISTS', 112);
if(!defined('CD_CREATE_FAILED'))	define('CD_CREATE_FAILED', 111);
if(!defined('CD_DELETE_FAILED'))	define('CD_DELETE_FAILED', 111);
//Patient Errors list
if(!defined('USR_CREATE_OK'))	define('USR_CREATE_OK', 100);
if(!defined('USR_UPDATE_OK'))	define('USR_UPDATE_OK', 100);
if(!defined('USR_FOUND_OK'))	define('USR_FOUND_OK', 100);
if(!defined('USR_CREATE_OK_W_ALERTS'))	define('USR_CREATE_OK_W_ALERTS', 101);
if(!defined('USR_CREATE_FAILED_REVIEW_INVALID_FIELDS'))	define('USR_CREATE_FAILED_REVIEW_INVALID_FIELDS', 102);
if(!defined('USR_UPDATE_FAILED_REVIEW_INVALID_FIELDS'))	define('USR_UPDATE_FAILED_REVIEW_INVALID_FIELDS', 102);
if(!defined('USR_ALREADY_EXIST'))	define('USR_ALREADY_EXIST', 103);
if(!defined('USR_CREATE_FAILED'))	define('USR_CREATE_FAILED', 104);
if(!defined('USR_UPDATE_FAILED'))	define('USR_UPDATE_FAILED', 104);
if(!defined('USR_UPDATE_ID_NOT_FOUND'))	define('USR_UPDATE_ID_NOT_FOUND', 105);
if(!defined('USR_DELETE_OK'))	define('USR_DELETE_OK', 100);
if(!defined('USR_DELETE_FAILED'))	define('USR_DELETE_FAILED', 104);
if(!defined('USR_PATIENT_NOT_FOUND_OK'))	define('USR_PATIENT_NOT_FOUND_OK', 106);
if(!defined('PATIENT_SUCCESSFUL_SIGNED_OUT'))	define('PATIENT_SUCCESSFUL_SIGNED_OUT', 100);
if(!defined('PATIENT_ALREADY_SIGNED_OUT'))	define('PATIENT_ALREADY_SIGNED_OUT', 103);
//alergies
if(!defined('ALERGYSET_CREATE_OK'))	define('ALERGYSET_CREATE_OK', 100);
if(!defined('ALERGYSET_IDPATIENT_INVALID'))	define('ALERGYSET_IDPATIENT_INVALID', 101);
if(!defined('ALERGYSET_REVIEW_ALERGY'))	define('ALERGYSET_REVIEW_ALERGY', 102);
if(!defined('ALERGIES_SUCCESSFUL_ANSWER'))	define('ALERGIES_SUCCESSFUL_ANSWER', 103);
if(!defined('ALERGIES_NO_EXIST'))	define('ALERGIES_NO_EXIST', 104);
if(!defined('ALERGIES_PATIENT_NO_EXIST'))	define('ALERGIES_PATIENT_NO_EXIST', 105);
//PFT
if(!defined('PFTSET_CREATE_OK'))	define('PFTSET_CREATE_OK', 100);
if(!defined('PFTSET_NOT_VALID'))	define('PFTSET_NOT_VALID', 106);
if(!defined('PFTSET_CLINICALDATA_NOT_EXISTS'))	define('PFTSET_CLINICALDATA_NOT_EXISTS', 101);
if(!defined('PFTSET_PATIENT_NOT_EXISTS'))	define('PFTSET_PATIENT_NOT_EXISTS', 102);
if(!defined('PFTSET_CREATE_OK_W_ERRORS'))	define('PFTSET_CREATE_OK_W_ERRORS', 103);
if(!defined('PFTUPDATE_CREATE_OK'))	define('PFTUPDATE_CREATE_OK', 100);
if(!defined('PFTUPDATE_PATIENT_NOT_EXISTS'))	define('PFTUPDATE_PATIENT_NOT_EXISTS', 102);
if(!defined('PFTUPDATE_CREATE_OK_W_ERRORS'))	define('PFTUPDATE_CREATE_OK_W_ERRORS', 103);
if(!defined('PFTSET_CREATE_OK_W_ERRORS_AND_WARNINGS'))	define('PFTSET_CREATE_OK_W_ERRORS_AND_WARNINGS', 104);
if(!defined('PFTSET_CREATE_OK_W_WARNINGS'))	define('PFTSET_CREATE_OK_W_WARNINGS', 105);
if(!defined('PFTUPDATE_CREATE_OK_W_ERRORS_AND_WARNINGS'))	define('PFTUPDATE_CREATE_OK_W_ERRORS_AND_WARNINGS', 104);
if(!defined('PFTUPDATE_CREATE_OK_W_WARNINGS'))	define('PFTUPDATE_CREATE_OK_W_WARNINGS', 105);
if(!defined('PFTUPDATE_PRESCRIPTION_NOT_EXISTS'))	define('PFTUPDATE_PRESCRIPTION_NOT_EXISTS', 101);
if(!defined('PFTUPDATE_SYNTAX_ERROR'))	define('PFTUPDATE_SYNTAX_ERROR', 104);
//Suitability
if(!defined('SUITABILITY_PRESCRIPTION_NOT_EXISTS'))	define('SUITABILITY_PRESCRIPTION_NOT_EXISTS', 101);
if(!defined('SUITABILITY_INCOMPLETE_INPUT_MEDSLIST'))	define('SUITABILITY_INCOMPLETE_INPUT_MEDSLIST', 102);
if(!defined('SUITABILITY_INVALID_INPUT_FORMAT'))	define('SUITABILITY_INVALID_INPUT_FORMAT', 103);
if(!defined('SUITABILITY_SET_CREATE_OK'))	define('SUITABILITY_SET_CREATE_OK', 100);
// login
if(!defined('LOGIN_SUCCSESFULLY'))	define('LOGIN_SUCCSESFULLY', 100);
if(!defined('LOGIN_FALSE'))	define('LOGIN_FALSE', 101);

//WRONG_PARAMETER
if(!defined('MISSING_OR_EMPTY_FIELD'))	define('MISSING_OR_EMPTY_FIELD', 901); //ERROR ESPECIAL
if(!defined('WRONG_PARAMETER'))	define('WRONG_PARAMETER', 901); //ERROR ESPECIAL
if(!defined('CONTROL_FAILURE'))	define('CONTROL_FAILURE', 911);
if(!defined('CONTROL_FAILURE_MSG'))	define('CONTROL_FAILURE_MSG', "HUBO UN ERROR EN EL SISTEMA POR FAVOR INTENTE MAS TARDE O CONTACTE ADMIN");
if(!defined('USR_FAILED_AUTHORIZATION'))	define('USR_FAILED_AUTHORIZATION', 912);
// MEDS
if(!defined('MEDS_PATIENT_NOT_EXIST'))	define('MEDS_PATIENT_NOT_EXIST', 101);	
if(!defined('MEDS_SUCCESSFUL_ANSWER'))	define('MEDS_SUCCESSFUL_ANSWER', 100);
if(!defined('MEDS_SUCCESSFUL_ANSWER_MSG'))	define('MEDS_SUCCESSFUL_ANSWER_MSG', "EL SERVIDOR HA RESPONDIDO");
if(!defined('MEDS_NOT_EXIST'))	define('MEDS_NOT_EXIST', 103);
	//STATUS
if(!defined('VISIT_STATUS'))	define('VISIT_STATUS', 2); //ERROR ESPECIAL
if(!defined('PATIENT_STATUS'))	define('PATIENT_STATUS', 1); //ERROR ESPECIAL
//PAH
if(!defined('PAH_SUCCESSFUL_ANSWER'))	define('PAH_SUCCESSFUL_ANSWER', 100);
if(!defined('PFC_SUCCESSFUL_ANSWER'))	define('PFC_SUCCESSFUL_ANSWER', 100);
	///Labels
if(!defined('MISSING_FIELD_LBL'))	define('MISSING_FIELD_LBL', "Este campo esta faltante ");
if(!defined('NOT_VALID_FIELD_LBL'))	define('NOT_VALID_FIELD_LBL', "Este campo no es valido ");
//ALERTS
if(!defined('ALERTS_SUCCESSFUL_ANSWER'))	define('ALERTS_SUCCESSFUL_ANSWER', 100);
if(!defined('ALERTS_PATIENT_NOT_EXIST'))	define('ALERTS_PATIENT_NOT_EXIST', 109);
if(!defined('ALERTS_HOSPITAL_NOT_EXIST'))	define('ALERTS_HOSPITAL_NOT_EXIST', 102);
if(!defined('ALERTS_SINTAX_ERROR'))	define('ALERTS_SINTAX_ERROR', 110);
if(!defined('ALERTS_ERROR'))	define('ALERTS_ERROR', 111);

//SEARCH
if(!defined('SEARCH_SUCCESSFUL_ANSWER'))	define('SEARCH_SUCCESSFUL_ANSWER', 100);
if(!defined('SEARCH_INVALID_FIELDS'))	define('SEARCH_INVALID_FIELDS', 103);
if(!defined('SEARCH_ENGINE_FAILURE'))	define('SEARCH_ENGINE_FAILURE', 104);
//LOGIN
if(!defined('LOGIN_SUCCESSFUL'))	define('LOGIN_SUCCESSFUL', 100);
if(!defined('LOGIN_USER_NOT_EXIST'))	define('LOGIN_USER_NOT_EXIST', 109);
if(!defined('LOGIN_APP_NOT_EXIST'))	define('LOGIN_APP_NOT_EXIST', 110);
//CHEMISTS
if(!defined('CA_SUCCESSFUL_ANSWER'))	define('CA_SUCCESSFUL_ANSWER', 100);
if(!defined('CA_SUCCESSFUL_ANSWER_NO_ACTIVE'))	define('CA_SUCCESSFUL_ANSWER_NO_ACTIVE', 101);
if(!defined('CA_SUCCESSFUL_ANSWER_NO'))	define('CA_SUCCESSFUL_ANSWER_NO', 102);
//STATISTICS KNOWN ERRORS
if(!defined('STATISTICS_SUCCESSFUL_ANSWER'))	define('STATISTICS_SUCCESSFUL_ANSWER', 100);
if(!defined('STATISTICS_PATIENT_NOT_EXIST'))	define('STATISTICS_PATIENT_NOT_EXIST', 109);
if(!defined('STATISTICS_HOSPITAL_NOT_EXIST'))	define('STATISTICS_HOSPITAL_NOT_EXIST', 102);
if(!defined('STATISTICS_SINTAX_ERROR'))	define('STATISTICS_SINTAX_ERROR', 110);
if(!defined('STATISTICS_ERROR'))	define('STATISTICS_ERROR', 111);
if(!defined('STATISTICS_TYPE_MISSING_MSG'))	define('STATISTICS_TYPE_MISSING_MSG', 'TIPO NO ESPECIFICADO, CONTACTE ADMIN');
if(!defined('STATISTICS_TYPE_WRONG_MSG'))	define('STATISTICS_TYPE_WRONG_MSG', 'PROPORCIONE UN TIPO CORRECTO, CONTACTE ADMIN');
if(!defined('STATISTICS_TYPE_MAX_NUM'))	define('STATISTICS_TYPE_MAX_NUM', 4);
if(!defined('STATISTICS_CHEMIST_MAX_NUM'))	define('STATISTICS_CHEMIST_MAX_NUM', 5);
if(!defined('STATISTICS_OPQUIMICO_WRONG_MSG'))	define('STATISTICS_OPQUIMICO_WRONG_MSG', 'PROPORCIONE UNA OPCION QUIMICO CORRECTA, CONTACTE ADMIN');
if(!defined('STATISTICS_DATE_WRONG_MSG'))	define('STATISTICS_DATE_WRONG_MSG', 'PROPORCIONE UNA FECHA CORRECTA, CONTACTE ADMIN');
if(!defined('STATISTICS_OPPACIENTE_WRONG_MSG'))	define('STATISTICS_OPPACIENTE_WRONG_MSG', 'PROPORCIONE UNA OPCION PACIENTE CORRECTA, CONTACTE ADMIN');
if(!defined('STATISTICS_PACIENTE_WRONG_MSG'))	define('STATISTICS_PACIENTE_WRONG_MSG', 'PROPORCIONE UN ID DE PACIENTE CORRECTO, CONTACTE ADMIN');
if(!defined('STATISTICS_PROPIEDAD_WRONG_MSG'))	define('STATISTICS_PROPIEDAD_WRONG_MSG', 'PROPORCIONE UNA PROPIEDAD CORRECTA, CONTACTE ADMIN');
if(!defined('STATISTICS_GENERO_WRONG_MSG'))	define('STATISTICS_GENERO_WRONG_MSG', 'PROPORCIONE UN GENERO CORRECTO, CONTACTE ADMIN');
if(!defined('STATISTICS_EDAD_WRONG_MSG'))	define('STATISTICS_EDAD_WRONG_MSG', 'PROPORCIONE UNA EDAD CORRECTA, CONTACTE ADMIN');
if(!defined('STATISTICS_ESTATUS_WRONG_MSG'))	define('STATISTICS_ESTATUS_WRONG_MSG', 'PROPORCIONE UN ESTATUS CORRECTO, CONTACTE ADMIN');
if(!defined('STATISTICS_SUCCESSFUL_ANSWER_MSG'))	define('STATISTICS_SUCCESSFUL_ANSWER_MSG', 'EL SERVIDOR HA RECIBIDO SU PETICION');
//HISTORY
if(!defined('HISTORY_SUCCESSFUL_ANSWER_MSG'))	define('HISTORY_SUCCESSFUL_ANSWER_MSG', 'EL SERVIDOR HA RECIBIDO SU PETICION');
if(!defined('HISTORY_ERROR_102_MSG'))	define('HISTORY_ERROR_102_MSG', 'HUBO UN PROBLEMA CONTACTE A ADMIN ERROR 102');
if(!defined('HISTORY_ERROR_101_MSG'))	define('HISTORY_ERROR_101_MSG', 'PROPORCIONE UN IDENTIFICADOR CORRECTO ERROR 101');
//INTERACTIONS
if(!defined('INTERACTION_POST_SUCCESS'))	define('INTERACTION_POST_SUCCESS', 100);
if(!defined('INTERACTION_NOT_VALID'))	define('INTERACTION_NOT_VALID', 101);
if(!defined('INTERACTION_PRESCRIPTION_NOT_EXIST'))	define('INTERACTION_PRESCRIPTION_NOT_EXIST', 102);
if(!defined('INTERACTION_TYPE_MED_FOOD'))	define('INTERACTION_TYPE_MED_FOOD', 1);
if(!defined('INTERACTION_TYPE_MED_MED'))	define('INTERACTION_TYPE_MED_MED', 2);
//Interaction
if(!defined('INTERACTION_SET_CREATE_OK'))	define('INTERACTION_SET_CREATE_OK', 100);
if(!defined('INTERACTION_PRESCRIPTION_NOT_EXISTS'))	define('INTERACTION_PRESCRIPTION_NOT_EXISTS', 102);
if(!defined('INTERACTION_HOSPITAL_UNKNOWN'))	define('INTERACTION_HOSPITAL_UNKNOWN', 103);
if(!defined('INTERACTION_PRESCRIPTION_UNKNOWN'))	define('INTERACTION_PRESCRIPTION_UNKNOWN', 104);
if(!defined('INTERACTION_MEDS_UNKNOWN'))	define('INTERACTION_MEDS_UNKNOWN', 105);
if(!defined('INTERACTION_INVALID_FIELDS'))	define('INTERACTION_INVALID_FIELDS', 106);

?>